[package]
name = "functor"
version = "0.1.0"
authors = ["Celio Grand <celiogrand@outlook.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/vorgv/functor/"

[dependencies]
